FROM php:8.1-apache


# prep folders and perms
RUN mkdir -p /var/www/html/episodes

# initialize env vars with defaults
# these can be changed with -e at docker run
ARG MP3_DIR=/var/www/html/episodes
ARG MP3_URL
ARG RECURSIVE_DIRECTORY_ITERATOR=true
ARG COPYRIGHT
ARG WEBMASTER
ARG ITUNES_OWNER_NAME
ARG ITUNES_OWNER_EMAIL
ARG LINK
ARG TITLE
ARG ITUNES_AUTHOR
ARG ITUNES_CATEGORIES
ARG ITUNES_EXPLICIT=false
ARG DESCRIPTION
ARG ITUNES_SUBTITLE
ARG ITUNES_SUMMARY
ARG ITUNES_SUBTITLE_SUFFIX
ARG ITUNES_TYPE
ARG LANGUAGE="en-us"
ARG ITEM_COUNT=10000
ARG AUTO_SAVE_COVER_ART=false
ARG MIN_FILE_AGE=30
ARG MIN_CACHE_TIME=5
ARG TTL=60
ARG FORCE_PASSWORD
ARG ATOM_TYPE
ARG DESCRIPTION_SOURCE
ARG DESCRIPTION_HMTL

ENV MP3_DIR=${MP3_DIR} \
    MP3_URL=${MP3_URL} \
    RECURSIVE_DIRECTORY_ITERATOR=$RECURSIVE_DIRECTORY_ITERATOR \
    COPYRIGHT=$COPYRIGHT \
    WEBMASTER=$WEBMASTER \
    ITUNES_OWNER_NAME=$ITUNES_OWNER_NAME \
    ITUNES_OWNER_EMAIL=$ITUNES_OWNER_EMAIL \
    LINK=$LINK \
    TITLE=$TITLE \
    ITUNES_AUTHOR=$ITUNES_AUTHOR \
    ITUNES_CATEGORIES=$ITUNES_CATEGORIES \
    ITUNES_EXPLICIT=$ITUNES_EXPLICIT \
    DESCRIPTION=$DESCRIPTION \
    ITUNES_SUBTITLE=$ITUNES_SUBTITLE \
    ITUNES_SUMMARY=$ITUNES_SUMMARY \
    ITUNES_SUBTITLE_SUFFIX=$ITUNES_SUBTITLE_SUFFIX \
    ITUNES_TYPE=$ITUNES_TYPE \
    LANGUAGE=$LANGUAGE \
    ITEM_COUNT=$ITEM_COUNT \
    AUTO_SAVE_COVER_ART=$AUTO_SAVE_COVER_ART \
    MIN_FILE_AGE=$MIN_FILE_AGE \
    MIN_CACHE_TIME=$MIN_CACHE_TIME \
    TTL=$TTL \
    FORCE_PASSWORD=$FORCE_PASSWORD \
    ATOM_TYPE=$ATOM_TYPE \
    DESCRIPTION_SOURCE=$DESCRIPTION_SOURCE \
    DESCRIPTION_HMTL=$DESCRIPTION_HMTL

# copy source files to docker 
COPY ./.htaccess/ /var/www/html/
COPY ./dir2cast.php /var/www/html/
COPY ./getID3/ /var/www/html/getID3/
COPY entrypoint.sh /usr/local/bin/
RUN a2enmod rewrite
ENTRYPOINT ["/bin/sh", "/usr/local/bin/entrypoint.sh"]
EXPOSE 80
CMD ["apache2-foreground"]