volumes:
  config:
    
services:
  podcast:
    image: ghcr.io/ctkcoding/dir2cast:main
    container_name: podcast
    restart: unless-stopped
    ports:
      - "2022:80"
    volumes:
      - episode_location:/var/www/html/episodes
      - config:/var/www/html
    # environment:
      # - MP3_URL = https://domain.com/episodes/
